### PR TITLE
SISRP-12095 - Using new grid type, alter UC-Planner CSS

### PR DESCRIPTION
**Pull request by darrylumich**
https://jira.berkeley.edu/browse/SISRP-12095

### CODE REVIEW

**Comment by marcpechaitis** [comment]
@darrylumich there was a build error...will you check it out?

**Comment by christianvuerings** [comment]
@darrylumich lgtm
@marcpechaitis would you like to do the merge?

**Comment by marcpechaitis** [comment]
@darrylumich merged.

Do you have access to upload to the server in DEV?

**Comment by darrylumich** [comment]
@marcpechaitis  Yup, just uploaded it.  Thanks for your help, sir!

**Comment by marcpechaitis** [comment]
@darrylumich don’t forget that when it is ready to migrate up the chain, you’re gonna have to request Shiva do it (via JIRA ticket)

**Pull request merged**
